if (IMGUI_PLATFORM_NAME STREQUAL "GLFW")
    message(STATUS "[ImGui] Including platform: ${IMGUI_PLATFORM_NAME}")
    list(APPEND IMGUI_PUBLIC_H_FILES ${IMGUI_BACKENDS_DIR}/imgui_impl_glfw.h)
    list(APPEND IMGUI_PUBLIC_CXX_FILES ${IMGUI_BACKENDS_DIR}/imgui_impl_glfw.cpp)
    if (EMSCRIPTEN)
        if (EMSCRIPTEN_VERSION VERSION_GREATER_EQUAL "3.1.57")
            message(STATUS "[ImGui] Using contrib.glfw3 for Emscripten ${IMGUI_PLATFORM_NAME} implementation")
            list(APPEND IMGUI_LINK_OPTIONS "--use-port=contrib.glfw3")
            list(APPEND IMGUI_COMPILE_OPTIONS "--use-port=contrib.glfw3")
        else ()
            message(STATUS "[ImGui] Using bundled Emscripten ${IMGUI_PLATFORM_NAME} implementation")
            list(APPEND IMGUI_LINK_OPTIONS "-sUSE_GLFW=3")
        endif ()
    else ()
        find_package(glfw3 CONFIG REQUIRED)
        list(APPEND IMGUI_EXTERNAL_LIBS glfw)
    endif ()
endif ()