include(backends/Allegro5Backend.cmake)

include(backends/platform/AndroidPlatform.cmake)
include(backends/platform/GLFWPlatform.cmake)
include(backends/platform/GLUTPlatform.cmake)
include(backends/platform/macOSPlatform.cmake)
include(backends/platform/SDL2Platform.cmake)
include(backends/platform/SDL3Platform.cmake)
include(backends/platform/Win32Platform.cmake)

include(backends/renderer/D3D9Renderer.cmake)
include(backends/renderer/D3D10Renderer.cmake)
include(backends/renderer/D3D11Renderer.cmake)
include(backends/renderer/D3D12Renderer.cmake)
include(backends/renderer/MetalRenderer.cmake)
include(backends/renderer/OpenGL2Renderer.cmake)
include(backends/renderer/OpenGL3Renderer.cmake)
include(backends/renderer/SDL2Renderer.cmake)
include(backends/renderer/SDL3Renderer.cmake)
include(backends/renderer/VulkanRenderer.cmake)
include(backends/renderer/WebGPURenderer.cmake)
